controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# filepath: /c:/Users/najma/Documents/B2/php-Symfony/Symfony/Ymmersions/config/routes.yaml
app_user_index:
    path: /user
    controller: App\Controller\UserController::index